image: node:lts

build:
    script:
        - npm install -g typescript webpack webpack-cli
        - npm install @types/chrome 
        - tsc --build tsconfig.json
        - npx webpack --entry ./build/Main.js --mode none
