image: nikolaik/python-nodejs:latest

cache:
    paths:
        - node_modules

stages:
    - install
    - code analysis
    - build

install:
    stage: install
    script:
        - npm install

code-analysis:
    stage: code analysis
    script:
        - python3 -m pip install -r pipeline-requirements.txt
        - python3 build.py --check

build:
    stage: build
    script:
        - npx tsc --build tsconfig.json
        - npx webpack --entry ./build/Main.js --mode none
