image: node:latest

build:
    script:
        - npm install -g typescript webpack webpack-cli
        - npm root -g
        - tsc --build tsconfig.json
        - npx webpack --entry ./build/Main.js --mode none
